### PR TITLE
The Frontend

### LINKED ISSUE #2: Work on frontend
Frontend needs to be worked on. I have already set it up for the most part (disregard CSS, just delete that) and will be working on the backend.
If you aren't sure if something will "mesh" properly with the backend, ask me and I'll take a look.

### PR DESCRIPTION
**Pull request by dudebehinddude**
If you commit to this branch tell me before you clone it but this branch won't be merged for a while until it gets to a reasonable state

This PR adds in a proper frontend to the site, DO NOT edit the .css file instead edit the .scss file and use [Live Sass Compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass)
Both the HTML and SCSS are formatted using [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) as this is what most people use

Closes #2

### CODE REVIEW

**Comment by 035WasTaken** [comment]
I understand this isn't completely done yet, but the text needs its own space to fit in. It can't just take up the entire space under the navbar. We aren't writing a book.

**Comment by 035WasTaken** [comment]
Another thing, you _are_ allowed to push a basic frontend you know? I need something to work with and you've made a lot of changes. You don't have to finish the whole thing, and in fact you _won't be able to_ if you don't give me something to work with. As of right now I have nothing to work with and am just idling by waiting for you. When you finish this then I'll be doing things that will then need someone on the frontend to handle (like displaying data) and it just won't be fun for anyone. There will be a lot of waiting and not a whole lot of doing things. This isn't a turn-based RPG, we actually do need to do things at somewhat the same time.

**Comment by dudebehinddude** [comment]
> I understand this isn't completely done yet, but the text needs its own space to fit in. It can't just take up the entire space under the navbar. We aren't writing a book.

Wdym by this

**Comment by dudebehinddude** [comment]
run the site locally and see what you think ;)

**Pull request merged**
